name: Fetch Stock Data Daily

on:
  schedule:
    - cron: '30 16 * * *'  # Runs every day at 10 PM IST (4:30 PM UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install yfinance

    - name: Run Python Script
      run: python fetch_data.py

    - name: Commit and Push Changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add stock_data.db
        git commit -m "Update stock data: $(date)"
        git push origin main --force
