name: Daily Stock Data Update

on:
  schedule:
    - cron: '30 16 * * *'  # 10 PM IST (16:30 UTC)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install yfinance

      - name: Run Python script
        run: python fetch_and_store.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "your-username"
          git add stocks_data.db
          git commit -m "Daily stock data update"
          git push origin main
